[string]$OPENCVINCLUDEPATH = $Env:SystemDrive+'\opencv\opencv-build\install\include'
[string]$OPENCVLIBPATH = $Env:SystemDrive+'\opencv\opencv-build\install\x64\mingw\lib'
[string]$OPENCVBINPATH = $Env:SystemDrive+'\opencv\opencv-build\install\x64\mingw\bin'
[string]$PYTHONPATH = $Env:SystemDrive+'\Python38'
# Write-Output $OPENCVINCLUDEPATH
# Write-Output $OPENCVLIBPATH
Write-Output "Compiling code samples..."
cp $Env:SystemDrive\Qt\5.12.2\mingw73_64\bin\Qt5Core.dll ../lib
cp $Env:SystemDrive\Qt\5.12.2\mingw73_64\bin\Qt5Gui.dll ../lib
cp $Env:SystemDrive\Qt\5.12.2\mingw73_64\bin\Qt5OpenGl.dll ../lib
cp $Env:SystemDrive\Qt\5.12.2\mingw73_64\bin\Qt5Test.dll ../lib
cp $Env:SystemDrive\Qt\5.12.2\mingw73_64\bin\Qt5Widgets.dll ../lib
cp ../lib/* .
g++ 001_stereo_panorama.cpp -I"$PYTHONPATH"\include -I"$PYTHONPATH"\Lib\site-packages\numpy\core\include -I"$OPENCVINCLUDEPATH"  -L"$PYTHONPATH" -lpython38 -L../lib -lPAL -lPAL_CAMERA -lPAL_DEPTH -lPAL_SSD -lPAL_DE -L"$OPENCVBINPATH"  -lopencv_core344 -lopencv_face344 -lopencv_videoio344 -lopencv_videoio344 -lopencv_imgproc344 -lopencv_highgui344 -lopencv_imgcodecs344 -lopencv_objdetect344 -lopencv_features2d344 -lopencv_video344 -lopencv_xfeatures2d344 -lopencv_ximgproc344 -lopencv_stereo344 -lopencv_calib3d344 -O3  -o 001_stereo_panorama.exe -I../include/ -lpthread
g++ 002_disparity_panorama.cpp -I"$PYTHONPATH"\include -I"$PYTHONPATH"\Lib\site-packages\numpy\core\include -I"$OPENCVINCLUDEPATH"  -L"$PYTHONPATH" -lpython38 -L../lib -lPAL -lPAL_CAMERA -lPAL_DEPTH -lPAL_SSD -lPAL_DE -L"$OPENCVBINPATH" -lopencv_core344 -lopencv_face344 -lopencv_videoio344 -lopencv_videoio344 -lopencv_imgproc344 -lopencv_highgui344 -lopencv_imgcodecs344 -lopencv_objdetect344 -lopencv_features2d344 -lopencv_video344 -lopencv_xfeatures2d344 -lopencv_ximgproc344 -lopencv_stereo344 -lopencv_calib3d344 -O3  -o 002_disparity_panorama.exe -I../include/ -lpthread
g++ 003_video_capture.cpp -I"$PYTHONPATH"\include -I"$PYTHONPATH"\Lib\site-packages\numpy\core\include -I"$OPENCVINCLUDEPATH" -L"$PYTHONPATH" -lpython38 -L../lib -lPAL -lPAL_CAMERA -lPAL_DEPTH -lPAL_SSD -lPAL_DE  -L"$OPENCVBINPATH" -lopencv_core344 -lopencv_face344 -lopencv_videoio344 -lopencv_videoio344 -lopencv_imgproc344 -lopencv_highgui344 -lopencv_imgcodecs344 -lopencv_objdetect344 -lopencv_features2d344 -lopencv_video344 -lopencv_xfeatures2d344 -lopencv_ximgproc344 -lopencv_stereo344 -lopencv_calib3d344 -O3  -o 003_video_capture.exe -I../include/ -lpthread
g++ 004_camera_properties.cpp -I"$PYTHONPATH"\include -I"$PYTHONPATH"\Lib\site-packages\numpy\core\include -I"$OPENCVINCLUDEPATH" -L"$PYTHONPATH" -lpython38 -L../lib -lPAL -lPAL_CAMERA -lPAL_DEPTH -lPAL_SSD -lPAL_DE -L"$OPENCVBINPATH" -lopencv_core344 -lopencv_face344 -lopencv_videoio344 -lopencv_videoio344 -lopencv_imgproc344 -lopencv_highgui344 -lopencv_imgcodecs344 -lopencv_objdetect344 -lopencv_features2d344 -lopencv_video344 -lopencv_xfeatures2d344 -lopencv_ximgproc344 -lopencv_stereo344 -lopencv_calib3d344 -O3  -o 004_camera_properties.exe -I../include/ -lpthread
g++ 005_resolutions.cpp -I"$PYTHONPATH"\include -I"$PYTHONPATH"\Lib\site-packages\numpy\core\include -I"$OPENCVINCLUDEPATH" -L"$PYTHONPATH" -lpython38 -L../lib -lPAL -lPAL_CAMERA -lPAL_DEPTH -lPAL_SSD -lPAL_DE -L"$OPENCVBINPATH" -lopencv_core344 -lopencv_face344 -lopencv_videoio344 -lopencv_videoio344 -lopencv_imgproc344 -lopencv_highgui344 -lopencv_imgcodecs344 -lopencv_objdetect344 -lopencv_features2d344 -lopencv_video344 -lopencv_xfeatures2d344 -lopencv_ximgproc344 -lopencv_stereo344 -lopencv_calib3d344 -O3  -o 005_resolutions.exe -I../include/ -lpthread
g++ 006_person_detections.cpp -I"$PYTHONPATH"\include -I"$PYTHONPATH"\Lib\site-packages\numpy\core\include -I"$OPENCVINCLUDEPATH" -L"$PYTHONPATH" -lpython38 -L../lib -lPAL -lPAL_CAMERA -lPAL_DEPTH -lPAL_SSD -lPAL_DE  -L"$OPENCVBINPATH" -lopencv_core344 -lopencv_face344 -lopencv_videoio344 -lopencv_videoio344 -lopencv_imgproc344 -lopencv_highgui344 -lopencv_imgcodecs344 -lopencv_objdetect344 -lopencv_features2d344 -lopencv_video344 -lopencv_xfeatures2d344 -lopencv_ximgproc344 -lopencv_stereo344 -lopencv_calib3d344 -O3  -o 006_person_detections.exe -I../include/ -lpthread
