[string]$OPENCVINCLUDEPATH = $Env:SystemDrive+'\opencv\opencv-build\install\include'
[string]$PYTHONPATH = $Env:SystemDrive+'\Python38'
[string]$OPENCVBINPATH = $Env:SystemDrive+'\opencv\opencv-build\install\x64\mingw\bin'
Write-Output "Compiling tutorials..."
cp ../lib/* .
g++ 001_cv_png.cpp  -I"$PYTHONPATH"\include -I"$PYTHONPATH"\Lib\site-packages\numpy\core\include -I"$OPENCVINCLUDEPATH" -L"$PYTHONPATH" -lpython38 -L../lib -lPAL -lPAL_CAMERA -lPAL_DEPTH -lPAL_SSD -lPAL_DE -L"$OPENCVBINPATH" -lopencv_core344 -lopencv_face344 -lopencv_videoio344 -lopencv_videoio344 -lopencv_imgproc344 -lopencv_highgui344 -lopencv_imgcodecs344 -lopencv_objdetect344 -lopencv_features2d344 -lopencv_video344 -lopencv_xfeatures2d344 -lopencv_ximgproc344 -lopencv_stereo344 -lopencv_calib3d344 -O3  -o 001_cv_png.exe -I../include/ -lpthread
g++ 002_set_properties.cpp -I"$PYTHONPATH"\include -I"$PYTHONPATH"\Lib\site-packages\numpy\core\include -I"$OPENCVINCLUDEPATH" -L../lib -lPAL -lPAL_CAMERA -lPAL_DEPTH -lPAL_SSD  -lPAL_DE -L"$PYTHONPATH" -lpython38 -L"$OPENCVBINPATH" -lopencv_core344 -lopencv_imgproc344 -lopencv_videoio344 -lopencv_calib3d344 -lopencv_highgui344 -lopencv_imgcodecs344 -lopencv_ximgproc344 -O3  -o 002_set_properties.exe -I../include/ -lpthread
g++ 003_disparity.cpp -I"$PYTHONPATH"\include -I"$PYTHONPATH"\Lib\site-packages\numpy\core\include -I"$OPENCVINCLUDEPATH" -L../lib -lPAL -lPAL_CAMERA -lPAL_DEPTH -lPAL_SSD  -lPAL_DE -L"$PYTHONPATH" -lpython38 -L"$OPENCVBINPATH" -lopencv_core344 -lopencv_imgproc344 -lopencv_videoio344 -lopencv_calib3d344 -lopencv_highgui344 -lopencv_imgcodecs344 -lopencv_ximgproc344 -O3  -o 003_disparity.exe -I../include/ -lpthread
g++ 004_point_cloud.cpp -I"$PYTHONPATH"\include -I"$PYTHONPATH"\Lib\site-packages\numpy\core\include -I"$OPENCVINCLUDEPATH" -L../lib -lPAL -lPAL_CAMERA -lPAL_DEPTH -lPAL_SSD  -lPAL_DE -L"$PYTHONPATH" -lpython38 -L"$OPENCVBINPATH" -lopencv_core344 -lopencv_imgproc344 -lopencv_videoio344 -lopencv_calib3d344 -lopencv_highgui344 -lopencv_imgcodecs344 -lopencv_ximgproc344 -O3  -o 004_point_cloud.exe -I../include/ -lpthread
